name: CMake

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
    - uses: actions/checkout@v2

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v1
      id: runvcpkg
      with:
        vcpkgArguments: '@${{ github.workspace }}/vcpkg-${{ runner.os }}.txt --triplet ${{ matrix.triplet }}'
        vcpkgGitCommitId: 'master'
        appendedCacheKey: '${{ github.workspace }}/vcpkg-${{ runner.os }}.txt'

    - name: 'Build with CMake and Ninja'
      uses: lukka/run-cmake@v2
      with:
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: got-${{ runner.os }}
        path: out/
