name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure CMake
      shell: bash
      run: cmake .

    - name: Build
      shell: bash
      run: cmake --build .
