name: CMake

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
    - uses: actions/checkout@v2

    - name: Cache vcpkg artifacts
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/vcpkg/
        # Ensure the cache is invalidated any time vcpkg version changes, or a different set of packages is being used.
        key: ${{ hashFiles( format('{0}/vcpkg-${{ runner.os }}.txt', github.workspace )) }}-${{ runner.os }}

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v1
      id: runvcpkg
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        vcpkgArguments: '@${{ github.workspace }}/vcpkg-${{ runner.os }}.txt --triplet ${{ matrix.triplet }}'
        vcpkgGitCommitId: 'master'

    - name: 'Build with CMake and Ninja'
      uses: lukka/run-cmake@v2
      with:
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: got-${{ runner.os }}
        path: out/
