name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure CMake
      shell: bash
      run: cmake .

    - name: Build
      shell: bash
      run: cmake --build .

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: got
        path: out/
